pipeline {
     agent any
// //     agent {
// //           docker {
// //               image 'maven:3-alpine'
// //               args '-v /root/.m2:/root/.m2'
// //           }
// //      }
     stages {
          stage('Build') {
              steps {
                  sh 'mvn package'
                  //batchFile 'docker build .'
                  //echo 'Hello!'
              }
          }
           stage('Test') {
               steps {
                   sh 'mvn test'
               }
               post {
                      always {
                          junit 'target/surefire-reports/*.xml'//./jenkins/scripts/deliver.sh
                      }
                  }
          }
           stage('Deliver') {
               steps {
                   sh 'docker build https://github.com/AmeyDevarshi/maven1.git#container:docker'
//                    sh 'docker run AmeyDevarshi/maven1' 
               }
           }
      }
 }


